# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'White', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'M', description: Faker::MostInterestingManInTheWorld.quote)
Cat.create(birth_date: '2014/01/20', color: 'Black', name: Faker::Pokemon.name, sex: 'F', description: Faker::MostInterestingManInTheWorld.quote)


CatRentalRequest.create(cat_id: 5, start_date: "01/01/2017", end_date: "03/01/2017", status:  "PENDING")
CatRentalRequest.create(cat_id: 5, start_date: "02/01/2017", end_date: "04/01/2017", status:  "PENDING")
CatRentalRequest.create(cat_id: 5, start_date: "05/01/2017", end_date: "08/01/2017", status:  "PENDING")
CatRentalRequest.create(cat_id: 5, start_date: "04/01/2017", end_date: "06/01/2017", status:  "PENDING")
CatRentalRequest.create(cat_id: 5, start_date: "02/01/2016", end_date: "03/01/2016", status:  "PENDING")
